import { writeFileSync, mkdirSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const HOME = homedir();
const CONFIG_DIR = join(HOME, ".config/lazydev");
const CONFIG_PATH = join(CONFIG_DIR, "config.yaml");

const DEFAULT_CONFIG = `# LazyDev Configuration
# Generated by 'lazydev init'

settings:
  proxy_port: 80
`;

const DNSMASQ_CONFIG = `# LazyDev DNS - wildcard *.localhost
address=/localhost/127.0.0.1
`;

export async function run() {
  console.log("Initializing LazyDev (proxy-only mode)...\n");
  
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
    console.log("✓ Created config directory:", CONFIG_DIR);
  }
  
  if (!existsSync(CONFIG_PATH)) {
    writeFileSync(CONFIG_PATH, DEFAULT_CONFIG);
    console.log("✓ Created config file:", CONFIG_PATH);
  } else {
    console.log("  Config file already exists:", CONFIG_PATH);
  }
  
  console.log("\n--- DNS Setup (dnsmasq) ---");
  
  const dnsmasqConfPath = "/etc/dnsmasq.d/lazydev";
  const dnsmasqExists = existsSync("/etc/dnsmasq.conf") || existsSync("/etc/dnsmasq.d");
  
  if (dnsmasqExists) {
    console.log("dnsmasq is installed.");
    console.log("\nRun these commands to complete setup:");
    console.log(`  echo '${DNSMASQ_CONFIG.trim()}' | sudo tee ${dnsmasqConfPath}`);
    console.log("  sudo systemctl enable --now dnsmasq");
  } else {
    console.log("dnsmasq not found. Install with:");
    console.log("  sudo dnf install dnsmasq");
    console.log("\nThen run: lazydev init");
    return;
  }
  
  console.log("\n--- Port 80 Setup ---");
  console.log("LazyDev needs port 80 for clean URLs (no port number).");
  console.log("This requires sudo once to allow binding to port 80.");
  console.log("\nRun:");
  console.log("  sudo setcap 'cap_net_bind_service=+ep' $(which bun)");
  console.log("\nThis allows bun to bind to privileged ports without sudo.");
  
  console.log("\n--- Done ---");
  console.log("Next steps:");
  console.log("  1. Start your dev server: cd ~/projects/myproject && bun dev");
  console.log("  2. Start proxy:       lazydev start");
  console.log("  3. Access at:         http://myproject.localhost");
  console.log("  4. Optional alias:    lazydev alias mp myproject");
}
